FROM apache/airflow:2.8.0
USER root
RUN apt-get update && apt-get install -y openjdk-17-jre-headless && apt-get clean
USER airflow
RUN pip install --no-cache-dir apache-airflow-providers-apache-spark pyspark==3.5.0
USER airflow
